### ISSUE TITLE
Migrate from API usage to Vercel Postgres including server actions (/api)

### ISSUE THREAD

**Issue by luanrv00** [luanrv00/tsks#1]
###### TODOS

- [ ] research best way to toggle "NEXT_PUBLIC_API_URL" to be "/api" while using
  Vercel PG
- [ ] setup Vercel PG using drizzle or knex
- [ ] implements server actions for db manipulation (/api)
